import { dbPool } from '../config/database';
import { logger } from '../utils/logger';
const tables = new Set(['products','product_variants','services','price_lists','service_areas','warranties','faqs','business_rules']);
const columns = new Set(['code','name','category','brand','description','specifications','unit','status','notes','source','last_verified_at','updated_by','product_id','service_id','product_variant_id','price','price_type','minimum_quantity','valid_from','valid_until','duration','conditions','keywords','question','answer','priority','rule_key','rule_name','rule_value','province','city']);
function check(table:string, body:Record<string,unknown>) { if(!tables.has(table)) throw new Error('Unsupported knowledge table'); const keys=Object.keys(body).filter(k=>columns.has(k)); if(!keys.length) throw new Error('No valid fields'); return keys; }
export async function listKnowledge(table:string, limit=50, offset=0) { if(!tables.has(table)) throw new Error('Unsupported knowledge table'); const r=await dbPool.query(`SELECT * FROM ${table} ORDER BY updated_at DESC LIMIT $1 OFFSET $2`,[Math.min(Math.max(limit,1),100),Math.max(offset,0)]); return r.rows; }
export async function getKnowledge(table:string, id:string) { if(!tables.has(table)) throw new Error('Unsupported knowledge table'); const r=await dbPool.query(`SELECT * FROM ${table} WHERE id=$1`,[id]); return r.rows[0]; }
export async function createKnowledge(table:string, body:Record<string,unknown>, actor='admin') { const keys=check(table,body); const vals=keys.map(k=>body[k]); if(!keys.includes('updated_by')) { keys.push('updated_by'); vals.push(actor); } const placeholders=keys.map((_,i)=>`$${i+1}`).join(','); const r=await dbPool.query(`INSERT INTO ${table} (${keys.join(',')}) VALUES (${placeholders}) RETURNING *`,vals); logger.info({table,action:'create',actor},'knowledge_admin_change'); return r.rows[0]; }
export async function updateKnowledge(table:string,id:string, body:Record<string,unknown>, actor='admin') { const keys=check(table,body); if(!keys.includes('updated_by')) { keys.push('updated_by'); body.updated_by=actor; } const vals=keys.map(k=>body[k]); const set=keys.map((k,i)=>`${k}=$${i+1}`).join(','); const r=await dbPool.query(`UPDATE ${table} SET ${set}, updated_at=now() WHERE id=$${keys.length+1} RETURNING *`,[...vals,id]); logger.info({table,action:'update',actor,found:r.rowCount},'knowledge_admin_change'); return r.rows[0]; }
export async function deleteKnowledge(table:string,id:string) { if(!tables.has(table)) throw new Error('Unsupported knowledge table'); await dbPool.query(`DELETE FROM ${table} WHERE id=$1`,[id]); }
